ex(PM, "en", False, [
 "B: Hi, I'm Beacon. What can I show you?",
 "V: We manage rental and resale for NRI owners in Kolkata and Chennai. Company is Harbourview Property Care.",
 "B: How many in your team, and enquiries per month?",
 "V: 16 property executives. 180 enquiries a month from our website and MagicBricks.",
 "B: How do you track them?",
 "V: Google Sheets. Owners keep asking for updates and we can't give quick reports.",
 "B: Here's the owner-wise Reports view you can share.",
 "V: I'm the director, it's my call. Please have sales call me, 90000 03140, sometime next quarter is fine."],
 role="director", seniority="executive", org={"name": "Harbourview Property Care", "type": "other_real_estate", "agents": 16},
 pain_points=["can't give owners quick reports"], current_tooling=["Google Sheets"], process="manual",
 geo={"countries": ["India"], "cities": ["Kolkata", "Chennai"]}, leads={"min": 180, "max": 180}, lead_sources=["website", "MagicBricks"],
 influence="approver", next_step="later", consent=True, contact={"phone": "+91 90000 03140"},
 ev={"role": [8], "seniority": [8], "organisation.name": [2], "organisation.type": [2], "organisation.agents": [4], "pain_points": [6], "current_tooling": [6],
     "process": [6], "geography": [2], "monthly_leads": [4], "lead_sources": [4], "influence": [8], "next_step": [8], "consent": [8], "contact": [8]})
ex(INT, "en", False, [
 "B: Hello, Beacon here. What brings you by?",
 "V: We're a turnkey interiors company in Bengaluru, working with handover buyers from big projects. 22 sales people.",
 "B: Leads per month?",
 "V: Around 1,000 from builder handover events and Google ads.",
 "B: Current tool?",
 "V: Salesforce. Too costly per seat and designers don't update it.",
 "B: Here's the simple mobile update flow for designers.",
 "V: I'm head of growth. I recommend, the CEO approves. We're deciding within 3 weeks. Yes, sales can email me at ananya.test@example.com."],
 role="head of growth", seniority="executive", org={"type": "other_real_estate", "agents": 22},
 pain_points=["too costly per seat", "designers don't update it"], current_tooling=["Salesforce"], process="unsatisfied_crm",
 geo={"countries": ["India"], "cities": ["Bengaluru"]}, leads={"min": 1000, "max": 1000}, lead_sources=["builder handover events", "Google ads"],
 influence="sponsored_evaluator", next_step="within_30_days", consent=True, contact={"email": "ananya.test@example.com"},
 ev={"role": [8], "seniority": [8], "organisation.type": [2], "organisation.agents": [2], "pain_points": [6], "current_tooling": [6],
     "process": [6], "geography": [2], "monthly_leads": [4], "lead_sources": [4], "influence": [8], "next_step": [8], "consent": [8], "contact": [8]})
