"""Reviewed English counterparts of every generic Hindi narration key."""

NARRATIONS_EN = {
    "module.dashboard": "This is your dashboard. The available charts and numbers give you an overview of your work. Check the date and team filters to focus on the information you need.",
    "module.leads": "This is the Leads list, where you can view customer enquiries and their status. Identify the right customer and owner before opening a record. Let's look at the available controls.",
    "module.data": "This is the Data module. You can find contacts using the list, search and available filters. Select the correct records before converting data into leads or assigning it to someone.",
    "module.invoice": "This is the Invoice screen. You can view the invoice-related records your account can access. Check the customer and amount before taking any action. This demo will not create an invoice.",
    "module.projects": "This is the Projects screen. You can find and view project information here. Linking projects and individual properties correctly helps you match them to customer requirements later.",
    "module.properties": "This is the Properties list. View property information and status here. Use the available filters to find properties that match a customer's budget, location and requirements.",
    "module.listing": "This is the Listing module. Your permissions determine which listings you can view. Check the selected listing's details before sharing it or making changes.",
    "module.tasks": "This is the Tasks screen. Review your work and its progress here. For a follow-up or another task, pay attention to the responsible person, date and status.",
    "module.reports": "This is the Reports screen. The results depend on the report, date range and team you select. Check the filters and time period before interpreting a report.",
    "module.users": "This is the Users list. View your organisation's members here. Check the right profile and your permissions before changing a person's information or responsibilities.",
    "module.teams": "This is Team Management. You can review teams and their members to understand responsibilities. This demonstration does not change anyone's team membership.",
    "module.roles": "This is the Roles screen. Roles determine which features a user can view or change. We're exploring the screen without changing anyone's permissions.",
    "module.attendance": "This is the Attendance screen. Use the available date and user filters to review attendance. Clock In and Clock Out change real attendance, so this demo will not press them.",
    "module.settings": "This is Global Configuration. Organisation-wide module settings and other options are available here. Changes may affect the whole team, so we'll identify the controls without changing settings.",
    "module.profile": "This is your Organisation Profile. Review the company's basic information here. Check the details and your permissions before editing. This demo makes no changes.",
    "field.name": "This is the customer's name. Enter a full name that makes the lead easy to identify. Notice the marker for required fields.",
    "field.phone": "This is the primary phone number. Check the country code and the customer's actual number. We won't enter a made-up phone number in this demo.",
    "field.alternate_phone": "This is the alternate phone number. Add a second contact number here if one is available.",
    "field.email": "This is the email field. Check that the address is typed correctly. Sample filling uses only a demonstration email address.",
    "field.source": "Lead Source tells you where the enquiry came from. Choose the correct source from the options available in your organisation.",
    "field.sub_source": "Sub-source identifies the enquiry's channel more precisely. Its options may depend on the main source you select.",
    "field.assignee": "The primary owner is the person responsible for this lead. Choose the right person based on your team and permissions.",
    "field.secondary_assignee": "The secondary owner can be another team member helping with the lead. Select someone only when needed.",
    "field.budget_min": "This is the minimum budget. Enter the lower end of the customer's budget and check the currency.",
    "field.budget_max": "This is the maximum budget. It should not be lower than the minimum. Together, these values help you find suitable properties.",
    "field.enquiry_type": "This is the enquiry type. Select the available option that matches the customer's requirement to classify the lead correctly.",
    "field.property_type": "This is the property type. Choose the kind of property the customer is looking for.",
    "field.bedrooms": "This is the bedroom requirement. Select the available option that matches how many bedrooms the customer needs.",
    "field.projects": "Select the projects the customer is interested in here. Identify the correct project in the list before adding it.",
    "field.properties": "Select properties related to the customer's enquiry here. Check their location, type and budget first.",
    "field.campaigns": "This is the campaign information. If the enquiry came from a marketing campaign, select the matching campaign when available.",
    "field.channel_partner": "This is the channel partner information. If a partner brought in the enquiry, link the correct partner here.",
    "field.location": "This is the enquired location. Select the area the customer is interested in so you can find suitable properties.",
    "field.company": "This is the customer's company information. Fill it in when it is known and relevant.",
    "field.designation": "This is the customer's designation or job title. Enter it here if you know the correct title.",
    "field.notes": "Use notes for a short description of the customer's needs and useful follow-up information. Keep the details relevant to the work.",
    "control.dashboard.overview": "This area shows the dashboard summary. Check the selected date range and filters before comparing the numbers.",
    "control.dashboard.filters": "These are the dashboard filters. Use the available date, team or other options to focus the information. We're identifying the controls without changing them.",
    "control.leads.add": "Use this Add Lead control to record a new enquiry. The form starts with the customer's identity, contact information and responsible owner.",
    "control.leads.status": "These filters group leads by status. Review the appropriate stage to decide which leads need your attention next.",
    "control.leads.grid": "This is the Leads list. Identify the correct record before reviewing its details, history or available actions. This demo does not change any customer record.",
    "control.settings.modules": "These are the module settings. They control options for your organisation. We're identifying where they are without changing them.",
    "control.settings.search": "Use this search to find a setting quickly. Understand what the setting affects before changing it.",
    "lead.open": "The Add Lead form is open. Let's go through the fields available on your screen. Some fields may differ depending on your organisation's setup and your permissions.",
    "lead.sample": "Only the sample name and email have been filled in. You still need to check the other required information yourself. No lead has been saved.",
    "tour.complete": "All available steps in this guide are complete. Use the screens and controls according to your responsibilities and permissions. No records were saved and no messages were sent. Ask for a module by name to explore it again.",
    "lead.complete": "The walkthrough of the available lead fields is complete. This is only a sample. Before creating a real lead, review the required fields, contact details, source and owner. You decide whether to save; the demo has not saved anything.",
    "voice.preview": "Hello! Let's explore Leadrat, one step at a time. You can pause the demonstration or replay the explanation whenever you like.",
}
