"""Source-reviewed communication and list guides; no write actions."""

# label, English detail, Hindi detail. The action executor owns the selectors.
HELP = {
    'communications': ('WhatsApp and email', 'The highlighted lead actions contain WhatsApp and Email. WhatsApp opens personal template sharing, integrated chat or the API composer according to account settings. Email opens SMTP, Brevo or template sharing. Each flow requires the relevant contact details and communication permission. Review recipient, template variables and message before sending. Neither channel has sent a message during this overview.', 'लीड के हाइलाइट किए गए actions में WhatsApp और Email हैं। WhatsApp से अकाउंट के अनुसार personal template, integrated chat या API फ़ॉर्म खुलता है। Email से SMTP, Brevo या template sharing खुलता है। दोनों में सही contact और communication permission चाहिए। भेजने से पहले recipient, template variables और message जाँचते हैं। इस overview में कोई संदेश नहीं भेजा है।'),
    'whatsapp': ('Lead WhatsApp', 'The WhatsApp icon opens the account-configured personal, integrated chat or API flow. Review the recipient number. In template sharing, open Template, choose an approved message and review its variables and message preview before Send. Integrated chat and API screens have different controls. This demo opens the available composer and template choices; it never sends a message.', 'WhatsApp आइकन से आपके अकाउंट का personal WhatsApp, integrated chat या API वाला फ़ॉर्म खुलता है। ग्राहक का नंबर जाँचें। Template sharing में टेम्पलेट चुनकर उसके variables और message preview जाँचते हैं। Integrated chat और API में कंट्रोल अलग हो सकते हैं। यह डेमो उपलब्ध फ़ॉर्म और टेम्पलेट विकल्प दिखाता है, संदेश भेजता नहीं है।'),
    'email': ('Lead email', 'The email icon opens the configured SMTP, Brevo or template-sharing screen. When both delivery choices are offered, this guide opens SMTP. Review recipient, sender, template, subject and message wherever those controls are available. A lead needs an email address and your account needs communication access. Review everything before Send; this demo does not send.', 'Email आइकन से configured SMTP, Brevo या template-sharing फ़ॉर्म खुलता है। दोनों विकल्प हों तो इस गाइड में SMTP खुलता है। उपलब्ध recipient, sender, template, subject और message जाँचें। लीड में ईमेल और अकाउंट में communication की अनुमति जरूरी है। डेमो ईमेल नहीं भेजता है।'),
    'sources': ('Lead sources', 'Lead Source and Sub Source describe attribution. Leads can enter through Add Lead, bulk file upload, Data conversion or configured integrations. The code includes Facebook, Google campaigns, property portals and webhook integrations. Source, campaign and channel partner fields are not proof an integration is enabled. Check Global Configuration for account setup and assignment rules.', 'Lead Source और Sub Source बताते हैं enquiry कहाँ से आई। लीड Add Lead, bulk upload, Data conversion या configured integration से आ सकती है। कोड में Facebook, Google campaigns, property portals और webhook integration मौजूद हैं। Source, campaign और channel partner फ़ील्ड होने का अर्थ integration चालू होना नहीं है। उसका setup और assignment Global Configuration में जाँचें।'),
    'bulk_upload': ('Lead bulk upload', 'Use the upload screen to supply the supported spreadsheet, map its columns to CRM fields, then review validation and import results. Follow the sample format offered by the screen. Correct invalid or duplicate entries before committing an import. This walkthrough does not choose a file or import customer records.', 'Upload स्क्रीन में समर्थित spreadsheet देते हैं, उसके कॉलम CRM फ़ील्ड से map करते हैं और validation तथा import result जाँचते हैं। स्क्रीन पर उपलब्ध sample format का उपयोग करें। Import करने से पहले गलत और duplicate entries जाँचें। डेमो फ़ाइल चुनता या रिकॉर्ड import नहीं करता।'),
    'filters': ('Advanced lead filters', 'Advanced Filters narrows the lead list using the available criteria. Choose criteria, review them and use the apply control. It changes which records you see, not the records themselves. The available fields depend on configuration and permissions.', 'Advanced Filters में उपलब्ध शर्तों से लीड लिस्ट छोटी करते हैं। शर्तें चुनकर जाँचें और Apply करें। इससे दिखने वाली लिस्ट बदलती है, लीड का डेटा नहीं। फ़ील्ड configuration और permissions पर निर्भर हैं।'),
    'search': ('Lead search', 'Use the lead search input and its search criteria selector to locate matching records. Select the appropriate criterion before entering the value. Search does not update a lead.', 'Search बॉक्स और उसके criteria selector से लीड ढूँढते हैं। सही criterion चुनकर value डालें। Search से लीड का डेटा नहीं बदलता।'),
    'columns': ('Lead columns', 'Manage Columns controls which columns appear in the lead grid. Review the available fields and keep the columns relevant to your work. The demo highlights this control without changing saved preferences.', 'Manage Columns से grid के कॉलम चुनते हैं। काम के अनुसार उपलब्ध फ़ील्ड देखें। डेमो कंट्रोल दिखाता है, आपकी saved preferences नहीं बदलता।'),
    'export': ('Lead export', 'The export control is permission-gated and can depend on organisation settings. Review the current list scope and filters before exporting. This guide only highlights the export control; it does not download customer data.', 'Export की सुविधा permission और organisation settings पर निर्भर है। Export से पहले लिस्ट और फ़िल्टर जाँचें। यह गाइड बटन दिखाती है, ग्राहक का डेटा डाउनलोड नहीं करती।'),
    'date_filter': ('Lead date filters', 'The date filter narrows results by the available date criterion and range. Check which date field is selected before setting a period; a created-date filter and an appointment-date filter answer different questions.', 'Date filter में सही date criterion और range चुनते हैं। समय चुनने से पहले देखें किस तारीख पर फ़िल्टर है। Created date और appointment date अलग जानकारी देते हैं।'),
    'saved_filters': ('Saved lead filters', 'Saved Filters reuses a filter configuration. Review its criteria before applying or setting a default. Saving a filter preserves a list preference rather than updating the selected customer records.', 'Saved Filters से पहले बनाई गई फ़िल्टर सेटिंग दोबारा इस्तेमाल करते हैं। Apply या default बनाने से पहले उसकी शर्तें जाँचें। इससे लिस्ट की preference सेव होती है, ग्राहक रिकॉर्ड नहीं बदलता।'),
    'integrations': ('Lead integrations', 'Global Configuration contains the integrations available to this account. The source includes Facebook, Google campaigns, Magicbricks, Housing, 99acres, Bayut, Dubizzle, Property Finder, Skyloov and webhook-related flows. Setup and assignment depend on provider and account permissions. This guide opens configuration without connecting accounts or changing rules.', 'Global Configuration में अकाउंट के उपलब्ध integrations देखें। कोड में Facebook, Google campaigns, Magicbricks, Housing, 99acres, Bayut, Dubizzle, Property Finder, Skyloov और webhook वाले फ़्लो हैं। Setup और assignment provider तथा permissions पर निर्भर हैं। डेमो अकाउंट connect या नियम नहीं बदलता।'),
}

EXTRA_FEATURES = {
    key: (label,
          [f"Let's open {label} and show the available controls.", english, 'Review the highlighted controls. No message was sent and no record was saved.'],
          [f'{label} के उपलब्ध कंट्रोल खोलकर दिखाता हूँ।', hindi, 'हाइलाइट किए गए कंट्रोल देखें। कोई संदेश नहीं भेजा और कोई रिकॉर्ड सेव नहीं किया गया है।'])
    for key, (label, english, hindi) in HELP.items()
}
